### ISSUE TITLE
update docker make targets

### ISSUE THREAD

**Issue by stchang** [racketscript/racketscript-playground#29]
Do docker make targets need to be updated to point to new repo locations?

**Comment by vishesh** [comment]
Dockerfile is installing RacketScript from pkgs.racket-lang.org. I updated the source there. So everything should work fine.

B/w using https://hub.docker.com/repository/docker/vishesh/racketscript-playground vs https://hub.docker.com/repository/docker/racketscript/racketscript-playground, I'd suggest using vishesh/racketscript, because it has free automated builds. The organizations feature on Docker Hub don't let you build images automatically for free.

**Comment by stchang** [comment]
ok got it
